package com.example.a41p.data;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Entity class representing an Event in the database.
 * Each instance of this class corresponds to a row in the "events" table.
 */
@Entity(tableName = "events")
public class Event {
    // Unique identifier for each event, automatically generated by Room
    @PrimaryKey(autoGenerate = true)
    private long id;
    
    // Title or name of the event
    private String title;
    
    // Category of the event (e.g., Work, Personal, Social)
    private String category;
    
    // Location where the event takes place
    private String location;
    
    // Date and time of the event stored as a timestamp (milliseconds since epoch)
    private long dateTime;

    /**
     * Constructor for creating a new Event instance.
     */
    public Event(String title, String category, String location, long dateTime) {
        this.title = title;
        this.category = category;
        this.location = location;
        this.dateTime = dateTime;
    }

    // Getters and Setters - Room uses these to access and update the private fields

    public long getId() { return id; }
    public void setId(long id) { this.id = id; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }

    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }

    public long getDateTime() { return dateTime; }
    public void setDateTime(long dateTime) { this.dateTime = dateTime; }
}
